apiVersion: apps/v1
kind: Deployment
metadata:
  name: quantfolio-app
  labels:
    app: quantfolio-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quantfolio-app
  template:
    metadata:
      labels:
        app: quantfolio-app
    spec:
      containers:
      - name: quantfolio-app
        image: amithpalissery/quantfolio-app:latest
        ports:
        - containerPort: 8501
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_REGION
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_REGION
